### ISSUE TITLE
 Allow adding other distances

### ISSUE THREAD

**Issue by igmagollo** [antoniocavalcante/mustache#8]
I'm a studant from UFSCar - Universidade Federal de São Carlos -  and in our research we are using **HDBSCAN*** with **Bray-Curtis dissimilarity** as the distance function. 

We'd like to use this app in our research to find more significant parameters in a efficient way, but untill now the most significant distance function we found for our problem was the **Bray-Curtis dissimilarity** and this app doesn't support this function.

I know it's hard to add other distance functions on demand and it isn't the best way.

You could allow people to add more distance functions if possible, or at least specify **where the IHDBSCAN.jar file comes from** and **how people can add other distance functions and compile this file again.**

**Comment by antoniocavalcante** [comment]
Hi Igor, thanks for your interest in MustaCHE. The jar file comes from the code in the following repo: 
https://github.com/antoniocavalcante/hdbscan-java

The code should be fairly easy to expand. There's a "distance" package with some dissimilarities measures, you can just implement your own. Should you generate another jar, the main class should be ExperimentIHDBSCANStar.

Because MustaCHE needs this other project but the other one does not need MustaCHE, I decided to keep them in different repositories. In the future, I plan on somehow linking them and making it easier to expand either one. Let me know if you have any trouble adding your dissimilarity function and integrating it into MustaCHE.

**Comment by igmagollo** [comment]
Thank you Antonio! It really helped me. I will close this issue, but I think it would be great if you put these instructions in a new section in the readme file so that others know how to do this at first reading.
