### ISSUE TITLE
Submitting csv and labels but nothing happens

### ISSUE THREAD

**Issue by olivatooo** [antoniocavalcante/mustache#9]
**Describe the bug**
After I upload the two csv files... Nothing happens
![image](https://user-images.githubusercontent.com/15200079/74655280-d9c26380-516a-11ea-82fb-1ab9c7d24b98.png)

**To Reproduce**
Load a csv data file
![image](https://user-images.githubusercontent.com/15200079/74655423-168e5a80-516b-11ea-9b11-046f4ae8fec3.png)
Load a csv data labels

**Expected behavior**
Some loading, some error, or just the output of the program

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 
 - Kernel: 5.5.4-arch1-1 
 - Browser: Mozilla Firefox 73.0

**Additional context**
It will be nice if the instructions have some sample data to test

**Comment by olivatooo** [comment]
The files:

[files.tar.gz](https://github.com/antoniocavalcante/mustache/files/4213913/files.tar.gz)

**Comment by antoniocavalcante** [comment]
Hi Gabriel, 

I'm sorry to hear that you're having trouble using MustaCHE. Thanks for reporting the bugs. These are known issues and I'll find the time soon to properly fix them in the code. In the meantime, there's a quick fix so you can get it running on your data. There are two things you need to do:

1 - Remove the duplicate entries on your input data CSV file. The code that computes the multiple hierarchies will crash in the background if duplicate data points are found. 
2 - Drop the file extension ".csv" from the input file. The naming convention used in the code will not take in consideration the extension of the file and will try and find files that do not exist.

Since I'm the sole developer of MustaCHE at the moment and my thesis has been taking more and more time as I approach the end of my program, it's been hard to jump back in the code and fix these issues. Let me know if you have any other problems and I'll look into them.

Cheers,

**Comment by olivatooo** [comment]
Hi! Thanks for the fast reply. 
Do you have some sample data that I can test?
MustaCHE works with multidimensional data?

**Comment by olivatooo** [comment]
I tried with this data in the example
![image](https://user-images.githubusercontent.com/15200079/74685185-84a74180-51ac-11ea-889e-8b8e1aae06dc.png)

Naming my data file as `data_1` and my labels file as `ids` following #7
